/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textioassignment;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author billc
 */
public class DrawingPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawingPanel
     */
    public DrawingPanel() {
        initComponents();
    }
    int scene = 0;

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("me_lol.PNG"));
        } catch (IOException e) {
        }

        BufferedImage img2 = null;
        try {
            img2 = ImageIO.read(new File("me_again_lol.JPG"));
        } catch (IOException e) {
        }

        LoginService login = new LoginService("info.txt");

        switch (scene) {
            case 0:
                g.drawImage(img1, 0, -225, this);
                break;
            case 1:
                g.drawImage(img2, -255, -225, this);
                Font font = new Font("Comic Sans MS", Font.BOLD, 16);
                g.setFont(font);
                g.drawString("\"The Thing cannot be described"
                        , this.getWidth()/2-100, 250);
                g.drawString("- there is no language for such abysms ", this.getWidth()/2-100, 275);
                g.drawString("of shrieking and immemorial lunacy, ", this.getWidth()/2-100, 300);
                g.drawString("such eldritch contradictions of all matter, ", this.getWidth()/2-100, 325);
                g.drawString("force, and cosmic order. A mountain walked ", this.getWidth()/2-100, 350);
                g.drawString("or stumbled.\"", this.getWidth()/2-100, 375);
                g.drawString("-Thurston (Johansen's journal), The Call of Cthulhu", this.getWidth()/2-100, 400);
                
                break;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
